---
- name: chess webserver config
  hosts: web
  tasks:
  - include_vars: 
      dir: group_vars/web
      extensions:
        - yml
        - yaml  
  - name: apt | update
    apt:
      update_cache: 'yes'
    notify:
    - apt | upgrade # is always called due to a bug on apt's side always reporting "changed" despite no new packages

  - name: apt | fail2ban
    apt:
      name: 'fail2ban'
      state: latest
      install_recommends: 'yes'
    notify:
    - failban | config
    - start and enable fail2ban

      
  - name: apt | apache2
    apt:
      name: ['apache2']
      state: latest
      install_recommends: 'yes'
    notify:
    - start and enable apache
    - ufw | http_port
    - ufw | https_port
      
  - name: apt | php
    apt: 
      name: ['php','php-mysql']
      state: latest
      install_recommends: 'yes'
  
  - name: apt | git
    apt: 
      name: git
      state: latest
    notify:
    - git | creds
  
  handlers:
  - name: start and enable fail2ban
    service:
      name: fail2ban
      state: restart
      enabled: 'yes'
  - name: fail2ban | config
    copy:
      src: ./files/jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: '0644'
  - name: start and enable apache
    service:
      name: apache2
      state: restart
      enabled: 'yes'
  - name: ufw | https_port
    ufw:
      rule: allow
      port: '{{ https_port }}'
      proto: tcp
  - name: ufw | http_port
    ufw:
      rule: allow
      port: '{{ http_port }}'
      proto: tcp
  - name: apt | upgrade
    apt:
      name: "*"
      state: latest
  - name: git | creds
    copy:
      src: "{{ local_home }}.ssh/id_rsa_github_personal"
      dest: "{{ remote_home }}.ssh/id_rsa_github_personal"
      mode: '0600'

- name: install db requirements
  hosts: db
  tasks:
  - name: apt | python goodies # required for sane install of pip
    apt:
      name: ['python3-pip','python3-venv','python3-dev', 'python-pip', 'python-dev']
      state: latest
  - name: pip | pymysql
    pip:
      name: pymysql

- name: get backups | db | website code
  hosts: web:db
  tasks:
  - include_vars: 
      dir: group_vars/db
      extensions:
        - yml
        - yaml
  - name: archive | /var/www 
    archive:
      path: /var/www
      dest: "{{ remote_home }}/web.tgz"
      force_archive: 'true'
    notify: 
    - fetch | archive /var/www
    - remove | archive
  
  - name: mysql | dump
    mysql_db:
      state: dump
      name: all
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_password }}"
      target: "{{ remote_home }}/alldbdump.sql"
    notify:
    - fetch | mysqldump
    - remove | mysqldump
  
  handlers:
  - name: fetch | archive /var/www
    fetch: 
      src: "{{ remote_home }}/web.tgz"
      dest: "{{ local_home }}/web.tgz"
      flat: 'yes'
  
  - name: remove | archive
    file:
      path: "{{ remote_home }}/www.zip"
      state: absent

  - name: fetch | mysqldump
    fetch:
      src: "{{ remote_home }}/alldbdump.sql"
      dest: "{{ local_home }}/alldbdump.sql"
      flat: 'yes'
  
  - name: remove | mysqldump
    file:
      path: "{{ remote_home }}/alldbdump.sql"
      state: absent
  

      